import {test} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import net from 'node:net';import {isPublicIP,webURL,resolvePublic,startProxy,pinnedProxyTarget,openChainedTunnel} from '../src/network.mjs';
test('block private, mapped, multicast, metadata and reserved addresses',()=>{for(const ip of ['127.0.0.1','10.1.2.3','172.16.0.1','192.168.1.1','169.254.169.254','100.64.0.1','0.0.0.0','::1','::ffff:127.0.0.1','fc00::1','fe80::1','224.0.0.1'])assert.equal(isPublicIP(ip),false,ip);assert.equal(isPublicIP('1.1.1.1'),true);});
test('reject private destination and non-web schemes',async()=>{await assert.rejects(resolvePublic('127.0.0.1'));for(const url of ['file:///etc/passwd','ftp://example.com','http://example.com:22'])assert.throws(()=>webURL(url));});
test('proxy rejects requests to loopback',async()=>{const p=await startProxy();try{const response=await fetch(p.url+'/');assert.equal(response.status,403);}finally{p.close();}});
test('upstream proxy endpoint must resolve to a public address',async()=>{await assert.rejects(startProxy('http://127.0.0.1:8080/'),/Private network/);});
test('normalized HTTP proxy without a serialized port uses port 80',async()=>{const proxy=await startProxy('http://93.184.216.34/');proxy.close();});
test('upstream requests use the validated destination IP while preserving URL path',()=>{assert.deepEqual(pinnedProxyTarget('http://example.com/path?q=1','1.1.1.1'),{authority:'1.1.1.1:80',absolute:'http://1.1.1.1:80/path?q=1'});assert.equal(pinnedProxyTarget('https://example.com/','2606:4700:4700::1111').authority,'[2606:4700:4700::1111]:443');});
test('chained HTTP routing pins CONNECT while preserving the origin-form Host request',async()=>{
 let resolveRequest;const received=new Promise(resolve=>{resolveRequest=resolve;});
 const server=net.createServer(socket=>{let phase='connect',buffer='';socket.on('data',chunk=>{buffer+=chunk.toString('latin1');const end=buffer.indexOf('\r\n\r\n');if(end<0)return;const header=buffer.slice(0,end+4);buffer=buffer.slice(end+4);if(phase==='connect'){assert.match(header,/^CONNECT 1\.1\.1\.1:80 HTTP\/1\.1/);assert.match(header,/\r\nHost: example\.com\r\n/);phase='request';socket.write('HTTP/1.1 200 Connection Established\r\n\r\n');if(buffer){resolveRequest(buffer);socket.end();}}else{resolveRequest(header+buffer);socket.end();}});});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{const socket=await openChainedTunnel({host:'127.0.0.1',family:4,port:server.address().port,authorization:null},'1.1.1.1:80','example.com');socket.write('GET /path?q=1 HTTP/1.1\r\nHost: example.com\r\n\r\n');const request=await received;assert.match(request,/^GET \/path\?q=1 HTTP\/1\.1/);assert.match(request,/\r\nHost: example\.com\r\n/);}finally{await new Promise(resolve=>server.close(resolve));}
});
test('complete chained HTTP forwarding uses the CONNECT tunnel',async()=>{
 let tunnelRequest;const upstream=net.createServer(socket=>{let phase='connect',buffer='';socket.on('data',chunk=>{buffer+=chunk.toString('latin1');const end=buffer.indexOf('\r\n\r\n');if(end<0)return;const header=buffer.slice(0,end+4);buffer=buffer.slice(end+4);if(phase==='connect'){assert.match(header,/^CONNECT 1\.1\.1\.1:80 HTTP\/1\.1/);phase='request';socket.write('HTTP/1.1 200 Connection Established\r\n\r\n');if(!buffer)return;}const request=phase==='request'?header+buffer:buffer;tunnelRequest=request;socket.end('HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\nok');});});
 await new Promise(resolve=>upstream.listen(0,'127.0.0.1',resolve));
 const resolve=async hostname=>hostname==='proxy.test'?{address:'127.0.0.1',family:4}:{address:'1.1.1.1',family:4};let proxy;
 try{proxy=await startProxy(`http://proxy.test:${upstream.address().port}/`,{resolve});const local=new URL(proxy.url);const response=await new Promise((resolveResponse,reject)=>{const request=http.request({host:local.hostname,port:local.port,path:'http://example.com/path?q=1',headers:{host:'example.com'}},res=>{let body='';res.setEncoding('utf8');res.on('data',chunk=>body+=chunk);res.on('end',()=>resolveResponse({status:res.statusCode,body}));});request.on('error',reject);request.end();});assert.deepEqual(response,{status:200,body:'ok'});assert.match(tunnelRequest,/^GET \/path\?q=1 HTTP\/1\.1/);assert.match(tunnelRequest,/\r\nHost: example\.com\r\n/i);}finally{proxy?.close();await new Promise(resolve=>upstream.close(resolve));}
});
test('tunnel negotiation rejects a clean premature EOF',async()=>{
 const server=net.createServer(socket=>socket.once('data',()=>socket.end()));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{await assert.rejects(openChainedTunnel({host:'127.0.0.1',family:4,port:server.address().port,authorization:null},'1.1.1.1:80','example.com'),/closed during tunnel negotiation/);}finally{await new Promise(resolve=>server.close(resolve));}
});
