const state=arguments[0],done=arguments[arguments.length-1],restore=state.restore||{};
const base64ToBytes=value=>Uint8Array.from(atob(value),character=>character.charCodeAt(0));
const decode=async value=>{
 if(value===null||typeof value!=='object')return value;
 if(Array.isArray(value))return Promise.all(value.map(decode));
 if(!value.__masaka){const result={};for(const key of Object.keys(value))result[key]=await decode(value[key]);return result;}
 if(value.__masaka==='object'&&value.value&&typeof value.value==='object'&&!Array.isArray(value.value)){const result={};for(const key of Object.keys(value.value))result[key]=await decode(value.value[key]);return result;}
 if(value.__masaka==='undefined')return undefined;
 if(value.__masaka==='number')return Number(value.value);
 if(value.__masaka==='bigint')return BigInt(value.value);
 if(value.__masaka==='date')return new Date(value.value);
 if(value.__masaka==='arraybuffer')return base64ToBytes(value.value).buffer;
 if(value.__masaka==='typedarray'){const bytes=base64ToBytes(value.value),Constructor=globalThis[value.name];if(typeof Constructor!=='function')throw new Error('Unknown typed array');return new Constructor(bytes.buffer);}
 if(value.__masaka==='blob')return new Blob([base64ToBytes(value.value)],{type:value.type});
 if(value.__masaka==='map')return new Map(await Promise.all(value.entries.map(async item=>[await decode(item[0]),await decode(item[1])])));
 if(value.__masaka==='set')return new Set(await Promise.all(value.values.map(decode)));
 if(value.__masaka==='cryptokey'){const material=value.format==='raw'?base64ToBytes(value.value):value.value;return crypto.subtle.importKey(value.format,material,value.algorithm,true,value.usages);}
 throw new Error('Unknown encoded value');
};
const sameKeyPath=(left,right)=>JSON.stringify(left??null)===JSON.stringify(right??null);
const installSchema=(request,database)=>{const wantedStores=new Set(database.stores.map(item=>item.name));for(const name of Array.from(request.result.objectStoreNames))if(!wantedStores.has(name))request.result.deleteObjectStore(name);for(const schema of database.stores){let store;if(!request.result.objectStoreNames.contains(schema.name))store=request.result.createObjectStore(schema.name,{keyPath:schema.keyPath??null,autoIncrement:!!schema.autoIncrement});else{store=request.transaction.objectStore(schema.name);if(!sameKeyPath(store.keyPath,schema.keyPath)||store.autoIncrement!==!!schema.autoIncrement){request.result.deleteObjectStore(schema.name);store=request.result.createObjectStore(schema.name,{keyPath:schema.keyPath??null,autoIncrement:!!schema.autoIncrement});}}const wantedIndexes=new Set((schema.indexes||[]).map(item=>item.name));for(const name of Array.from(store.indexNames))if(!wantedIndexes.has(name))store.deleteIndex(name);for(const index of schema.indexes||[]){if(!store.indexNames.contains(index.name))store.createIndex(index.name,index.keyPath,{unique:!!index.unique,multiEntry:!!index.multiEntry});else{const current=store.index(index.name);if(!sameKeyPath(current.keyPath,index.keyPath)||current.unique!==!!index.unique||current.multiEntry!==!!index.multiEntry){store.deleteIndex(index.name);store.createIndex(index.name,index.keyPath,{unique:!!index.unique,multiEntry:!!index.multiEntry});}}}}};
const openDatabaseAtVersion=(database,version)=>new Promise((resolve,reject)=>{const request=indexedDB.open(database.name,version);request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('IndexedDB open blocked'));request.onupgradeneeded=()=>{try{installSchema(request,database);}catch(error){try{request.transaction.abort();}catch{}reject(error);}};request.onsuccess=()=>resolve(request.result);});
const createDatabase=(database,existing)=>{if(!existing)return openDatabaseAtVersion(database,Math.max(1,Number(database.version)||1));return new Promise((resolve,reject)=>{const request=indexedDB.open(database.name);request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('IndexedDB open blocked'));request.onsuccess=()=>{const current=request.result;try{const wantedStores=new Set(database.stores.map(item=>item.name));let upgrade=Array.from(current.objectStoreNames).some(name=>!wantedStores.has(name));for(const schema of database.stores){if(!current.objectStoreNames.contains(schema.name)){upgrade=true;continue}const store=current.transaction(schema.name,'readonly').objectStore(schema.name),wantedIndexes=new Set((schema.indexes||[]).map(item=>item.name));if(!sameKeyPath(store.keyPath,schema.keyPath)||store.autoIncrement!==!!schema.autoIncrement||Array.from(store.indexNames).some(name=>!wantedIndexes.has(name))){upgrade=true;continue}for(const index of schema.indexes||[]){if(!store.indexNames.contains(index.name)){upgrade=true;continue}const saved=store.index(index.name);if(!sameKeyPath(saved.keyPath,index.keyPath)||saved.unique!==!!index.unique||saved.multiEntry!==!!index.multiEntry)upgrade=true;}}if(!upgrade){resolve(current);return}const nextVersion=Math.max(Number(current.version)+1,Number(database.version)||1);current.close();openDatabaseAtVersion(database,nextVersion).then(resolve,reject);}catch(error){current.close();reject(error);}};});};
const deleteDatabase=name=>new Promise((resolve,reject)=>{const request=indexedDB.deleteDatabase(name);request.onerror=()=>reject(request.error||new Error('IndexedDB delete failed'));request.onblocked=()=>reject(new Error('IndexedDB delete blocked'));request.onsuccess=()=>resolve();});
const decodeStore=async schema=>({schema,records:await Promise.all((schema.records||[]).map(async record=>({key:await decode(record.key),value:await decode(record.value)})))});
const writeStore=(database,prepared)=>new Promise((resolve,reject)=>{const {schema,records}=prepared;if(!database.objectStoreNames.contains(schema.name)){reject(new Error('IndexedDB schema changed'));return}const transaction=database.transaction(schema.name,'readwrite'),store=transaction.objectStore(schema.name);transaction.onerror=()=>reject(transaction.error);transaction.onabort=()=>reject(transaction.error||new Error('IndexedDB transaction aborted'));transaction.oncomplete=()=>resolve();store.clear();for(const record of records){if(schema.keyPath===null||schema.keyPath===undefined)store.put(record.value,record.key);else store.put(record.value);}});
(async()=>{
 if(restore.local_storage!==false){localStorage.clear();for(const item of state.local_storage||[])localStorage.setItem(item.name,item.value);}
 if(restore.session_storage!==false){sessionStorage.clear();for(const item of state.session_storage||[])sessionStorage.setItem(item.name,item.value);}
 const existing=new Set((typeof indexedDB.databases==='function'?await indexedDB.databases():[]).map(item=>item.name).filter(Boolean));
 if(restore.indexed_db!==false){const preparedDatabases=await Promise.all((state.indexed_db||[]).map(async schema=>({schema,stores:await Promise.all((schema.stores||[]).map(decodeStore))}))),savedNames=new Set(preparedDatabases.map(item=>item.schema.name));for(const name of existing)if(!savedNames.has(name))await deleteDatabase(name);for(const prepared of preparedDatabases){const alreadyExists=existing.has(prepared.schema.name),database=await createDatabase(prepared.schema,alreadyExists);try{for(const store of prepared.stores)await writeStore(database,store);}finally{database.close();}}}
 if(restore.cache_storage!==false&&typeof caches!=='undefined'){
  const savedCaches=state.cache_storage||[],savedNames=new Set(savedCaches.map(item=>item.name));for(const name of await caches.keys())if(!savedNames.has(name))await caches.delete(name);
  for(const saved of savedCaches){const entries=saved.entries||[];await caches.delete(saved.name);const cache=await caches.open(saved.name);for(const entry of entries){const status=Number(entry.response.status);if(status===0||status<200||status>599)continue;const request=new Request(entry.request.url,{method:entry.request.method||'GET',headers:entry.request.headers||[]}),body=[204,205,304].includes(status)?null:base64ToBytes(entry.response.body),response=new Response(body,{status,statusText:entry.response.statusText,headers:entry.response.headers||[]});await cache.put(request,response);}}
 }
 done({ok:true});
})().catch(error=>done({__masaka_error:String(error?.message||error).slice(0,2000)}));
